/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Aa: typeof import('./src/components/aa.vue')['default']
    Banner: typeof import('./src/components/Banner.vue')['default']
    BottomBar: typeof import('./src/components/BottomBar.vue')['default']
    CardDetail: typeof import('./src/components/CardDetail.vue')['default']
    CreateMessage: typeof import('./src/components/CreateMessage.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    FootBar: typeof import('./src/components/FootBar.vue')['default']
    FooterBar: typeof import('./src/components/FooterBar.vue')['default']
    FooterBar1: typeof import('./src/components/FooterBar1.vue')['default']
    HeaderBar: typeof import('./src/components/HeaderBar.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MessageCard: typeof import('./src/components/MessageCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
